### ISSUE TITLE
Allow running in-parallel add-ons

### ISSUE THREAD

**Issue by issacg** [issacg/hassio-addon-devcontainer#1]
Expected behavior: As a user, I should be able to develop several add-ons in the same Hass.io instance.

Actual behavior: Each add-on needs to run in its own devcontainer

**Comment by issacg** [comment]
When https://github.com/microsoft/vscode-remote-release/issues/2129 is solved, each add-on should be able to mount to the same running container under local add-ons.

Until then, as a workaround, you can modify the `workspaceMount` and `workspaceFolder` to the respective parent folders and then all add-ons in the parent directory will show up in the local add-ons

**Comment by inverse** [comment]
@issacg can this be closed and the readme updated? As the ticket in question was closed.

**Comment by issacg** [comment]
Not sure if it works as expected, as it hasn't been tested AFAIK.

Regardless, one could use the same setup as https://github.com/home-assistant/addons to achieve a similar goal, should one desire.
