### ISSUE TITLE
Local add-on testing documentation correct? 

### ISSUE THREAD

**Issue by inverse** [issacg/hassio-addon-devcontainer#5]
Is the documentation for local add-on testing correct?

When I follow the steps I don't have any tasks to start Home Assistant. I notice that there is a `.vscode` folder which includes such tasks - https://github.com/home-assistant/addons/blob/master/.vscode/tasks.json

However this will need to be modified to support the extension under test if I am not mistaken.

Cross posted from here: https://github.com/home-assistant/developers.home-assistant/issues/765 as they didn't seem to think that repo was the correct place to raise it.

**Comment by issacg** [comment]
Asking here is fine, too as far as I'm concerned - no worries.

I just did a fresh clone and followed the instructions as listed in the local add-on testing page, and they seem to be accurate.  Home-Assistant bootstrapped as expected, and the "Demo Add-on" was found, and could be installed and run as expected.

The task to start Home Assistant is in Terminal --> Run Task

If you can't find it, perhaps attach a screenshot of what you're seeing?

**Comment by inverse** [comment]
Thanks @issacg for reaching back. I followed the stand alone instructions detailed on the page (using this repo as a base) and so far so good - thanks for this awesome template by the way!

It was more confusion around the steps listed above which felt more incomplete which didn't work for me.

![image](https://user-images.githubusercontent.com/713525/103950779-cb43b880-513d-11eb-893d-b0edc536f199.png)


However in hindsight perhaps I was misinterpreting as what should be done for stand alone development which should be using your template - which actually does work.

Feel free to close this in such case.

**Comment by issacg** [comment]
Great.  Closing.

The big difference is that the Home Assistant team keeps the one from the Official Add-Ons up-to-date and I don't have the time to backport them all (but patches are welcome :))
