### ISSUE TITLE
Volume increase on starting home assistant

### ISSUE THREAD

**Issue by inverse** [issacg/hassio-addon-devcontainer#7]
I noticed that whenever I start the home assistant task the volume output changes to max volume which is pretty annoying.

I suspect it's something to do with the home-assistant init. 

Any ideas on how to prevent this?

I'm on Linux

```
21-04-15 20:58:19 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-hassio-audio with tag 2021.02.1.
21-04-15 20:58:26 INFO (MainThread) [supervisor.plugins.audio] Audio plugin now installed
21-04-15 20:58:26 INFO (MainThread) [supervisor.plugins.audio] Starting Audio plugin
21-04-15 20:58:27 INFO (SyncWorker_0) [supervisor.docker.audio] Starting Audio homeassistant/amd64-hassio-audio with version 2021.02.1 - 172.30.32.4
```

**Comment by issacg** [comment]
Hey,

I'm not sure what the underlying issue is, but the description and the log files you chose to quote both point at https://github.com/home-assistant/plugin-audio  

I'd suggest opening an issue there asking.

**Comment by inverse** [comment]
@issacg thanks for pointing me in the right direction. Will close here.
